[package]
name = "binocle"
version = "0.1.0"
edition = "2018"
resolver = "2"

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
colorgrad = "0.5"
egui = "0.14"
egui_wgpu_backend = "0.12"
egui_winit_platform = { version = "0.10" }
env_logger = "0.9"
log = "0.4"
pixels = "0.6"
winit = "0.25"
winit_input_helper = "0.10"
anyhow = "1.0"
humansize = "1.1"